apiVersion: v1
kind: Secret
metadata:
  name: mimir-bucket-secret
  namespace: grafana-mimir
data:
  AWS_ACCESS_KEY_ID: 'Z3JhZmFuYS1taW1pci1zYQo='
  AWS_SECRET_ACCESS_KEY: 'eDJqSjBUSmE4WWhkeHJNTXlZS25rWDJaaVVmMHFkVFEK'
